TRUNCATE TABLE Category

INSERT into [dbo].[Category] ([CategoryName], [CreatedOn], [CreatedBy], [CategoryGroupId]) VALUES (N'appliances', CAST(0xA1F304F9 AS SmallDateTime), 1, 1)
INSERT into [dbo].[Category] ([CategoryName], [CreatedOn], [CreatedBy], [CategoryGroupId]) VALUES (N'antiques', CAST(0xA1F304F9 AS SmallDateTime), 1, 1)
INSERT into [dbo].[Category] ([CategoryName], [CreatedOn], [CreatedBy], [CategoryGroupId]) VALUES (N'barter', CAST(0xA1F304F9 AS SmallDateTime), 1, 1)
INSERT into [dbo].[Category] ([CategoryName], [CreatedOn], [CreatedBy], [CategoryGroupId]) VALUES (N'bikes', CAST(0xA1F304F9 AS SmallDateTime), 1, 1)
INSERT into [dbo].[Category] ([CategoryName], [CreatedOn], [CreatedBy], [CategoryGroupId]) VALUES (N'boats', CAST(0xA1F304F9 AS SmallDateTime), 1, 1)
INSERT into [dbo].[Category] ([CategoryName], [CreatedOn], [CreatedBy], [CategoryGroupId]) VALUES (N'books', CAST(0xA1F304F9 AS SmallDateTime), 1, 1)
INSERT into [dbo].[Category] ([CategoryName], [CreatedOn], [CreatedBy], [CategoryGroupId]) VALUES (N'business', CAST(0xA1F304F9 AS SmallDateTime), 1, 1)
INSERT into [dbo].[Category] ([CategoryName], [CreatedOn], [CreatedBy], [CategoryGroupId]) VALUES (N'computer', CAST(0xA1F304F9 AS SmallDateTime), 1, 1)
INSERT into [dbo].[Category] ([CategoryName], [CreatedOn], [CreatedBy], [CategoryGroupId]) VALUES (N'free', CAST(0xA1F304F9 AS SmallDateTime), 1, 1)
INSERT into [dbo].[Category] ([CategoryName], [CreatedOn], [CreatedBy], [CategoryGroupId]) VALUES (N'furniture', CAST(0xA1F304F9 AS SmallDateTime), 1, 1)
INSERT into [dbo].[Category] ([CategoryName], [CreatedOn], [CreatedBy], [CategoryGroupId]) VALUES (N'general', CAST(0xA1F304F9 AS SmallDateTime), 1, 1)
INSERT into [dbo].[Category] ([CategoryName], [CreatedOn], [CreatedBy], [CategoryGroupId]) VALUES (N'jewelry', CAST(0xA1F304F9 AS SmallDateTime), 1, 1)
INSERT into [dbo].[Category] ([CategoryName], [CreatedOn], [CreatedBy], [CategoryGroupId]) VALUES (N'materials', CAST(0xA1F304F9 AS SmallDateTime), 1, 1)
INSERT into [dbo].[Category] ([CategoryName], [CreatedOn], [CreatedBy], [CategoryGroupId]) VALUES (N'rvs', CAST(0xA1F304F9 AS SmallDateTime), 1, 1)
INSERT into [dbo].[Category] ([CategoryName], [CreatedOn], [CreatedBy], [CategoryGroupId]) VALUES (N'sporting', CAST(0xA1F304F9 AS SmallDateTime), 1, 1)
INSERT into [dbo].[Category] ([CategoryName], [CreatedOn], [CreatedBy], [CategoryGroupId]) VALUES (N'tickets', CAST(0xA1F304F9 AS SmallDateTime), 1, 1)
INSERT into [dbo].[Category] ([CategoryName], [CreatedOn], [CreatedBy], [CategoryGroupId]) VALUES (N'tools', CAST(0xA1F304F9 AS SmallDateTime), 1, 1)
INSERT into [dbo].[Category] ([CategoryName], [CreatedOn], [CreatedBy], [CategoryGroupId]) VALUES (N'wanted', CAST(0xA1F304F9 AS SmallDateTime), 1, 1)
INSERT into [dbo].[Category] ([CategoryName], [CreatedOn], [CreatedBy], [CategoryGroupId]) VALUES (N'arts+crafts', CAST(0xA1F304F9 AS SmallDateTime), 1, 1)
INSERT into [dbo].[Category] ([CategoryName], [CreatedOn], [CreatedBy], [CategoryGroupId]) VALUES (N'auto parts', CAST(0xA1F304F9 AS SmallDateTime), 1, 1)
INSERT into [dbo].[Category] ([CategoryName], [CreatedOn], [CreatedBy], [CategoryGroupId]) VALUES (N'baby+kids', CAST(0xA1F304F9 AS SmallDateTime), 1, 1)
INSERT into [dbo].[Category] ([CategoryName], [CreatedOn], [CreatedBy], [CategoryGroupId]) VALUES (N'beauty+hlth', CAST(0xA1F304F9 AS SmallDateTime), 1, 1)
INSERT into [dbo].[Category] ([CategoryName], [CreatedOn], [CreatedBy], [CategoryGroupId]) VALUES (N'cars+trucks', CAST(0xA1F304F9 AS SmallDateTime), 1, 1)
INSERT into [dbo].[Category] ([CategoryName], [CreatedOn], [CreatedBy], [CategoryGroupId]) VALUES (N'cds/dvd/vhs', CAST(0xA1F304F9 AS SmallDateTime), 1, 1)
INSERT into [dbo].[Category] ([CategoryName], [CreatedOn], [CreatedBy], [CategoryGroupId]) VALUES (N'cell phones', CAST(0xA1F304F9 AS SmallDateTime), 1, 1)
INSERT into [dbo].[Category] ([CategoryName], [CreatedOn], [CreatedBy], [CategoryGroupId]) VALUES (N'clothes+acc', CAST(0xA1F304F9 AS SmallDateTime), 1, 1)
INSERT into [dbo].[Category] ([CategoryName], [CreatedOn], [CreatedBy], [CategoryGroupId]) VALUES (N'collectibles', CAST(0xA1F304F9 AS SmallDateTime), 1, 1)
INSERT into [dbo].[Category] ([CategoryName], [CreatedOn], [CreatedBy], [CategoryGroupId]) VALUES (N'electronics', CAST(0xA1F304F9 AS SmallDateTime), 1, 1)
INSERT into [dbo].[Category] ([CategoryName], [CreatedOn], [CreatedBy], [CategoryGroupId]) VALUES (N'farm+garden', CAST(0xA1F304F9 AS SmallDateTime), 1, 1)
INSERT into [dbo].[Category] ([CategoryName], [CreatedOn], [CreatedBy], [CategoryGroupId]) VALUES (N'garage sale', CAST(0xA1F304F9 AS SmallDateTime), 1, 1)
INSERT into [dbo].[Category] ([CategoryName], [CreatedOn], [CreatedBy], [CategoryGroupId]) VALUES (N'household', CAST(0xA1F304F9 AS SmallDateTime), 1, 1)
INSERT into [dbo].[Category] ([CategoryName], [CreatedOn], [CreatedBy], [CategoryGroupId]) VALUES (N'motorcycles', CAST(0xA1F304F9 AS SmallDateTime), 1, 1)
INSERT into [dbo].[Category] ([CategoryName], [CreatedOn], [CreatedBy], [CategoryGroupId]) VALUES (N'music instr', CAST(0xA1F304F9 AS SmallDateTime), 1, 1)
INSERT into [dbo].[Category] ([CategoryName], [CreatedOn], [CreatedBy], [CategoryGroupId]) VALUES (N'photo+video', CAST(0xA1F304F9 AS SmallDateTime), 1, 1)
INSERT into [dbo].[Category] ([CategoryName], [CreatedOn], [CreatedBy], [CategoryGroupId]) VALUES (N'toys+games', CAST(0xA1F304F9 AS SmallDateTime), 1, 1)
INSERT into [dbo].[Category] ([CategoryName], [CreatedOn], [CreatedBy], [CategoryGroupId]) VALUES (N'video gaming', CAST(0xA1F304F9 AS SmallDateTime), 1, 1)

TRUNCATE TABLE CATEGORYGROUP

INSERT INTO CategoryGroup VALUES('General',GETDATE(),1)
